using Binance.Net.Converters;
using Binance.Net.Enums;

namespace Binance.Net.Objects.Models
{
    /// <summary>
    /// Order info
    /// </summary>
    [SerializationModel]
    public record BinanceOrderBase
    {
        /// <summary>
        /// ["<c>symbol</c>"] The symbol the order is for
        /// </summary>
        [JsonPropertyName("symbol")]
        public string Symbol { get; set; } = string.Empty;
        /// <summary>
        /// ["<c>orderId</c>"] The order id generated by Binance
        /// </summary>
        [JsonPropertyName("orderId")]
        public long Id { get; set; }

        /// <summary>
        /// ["<c>orderListId</c>"] Id of the order list this order belongs to
        /// </summary>
        [JsonPropertyName("orderListId")]
        public long OrderListId { get; set; }

        /// <summary>
        /// ["<c>origClientOrderId</c>"] Original order id
        /// </summary>
        [JsonPropertyName("origClientOrderId")]
        [JsonConverter(typeof(ClientOrderIdReplaceConverter))]
        public string OriginalClientOrderId { get; set; } = string.Empty;

        /// <summary>
        /// ["<c>clientOrderId</c>"] The order id as assigned by the client
        /// </summary>
        [JsonPropertyName("clientOrderId")]
        [JsonConverter(typeof(ClientOrderIdReplaceConverter))]
        public string ClientOrderId { get; set; } = string.Empty;

        private decimal _price;

        /// <summary>
        /// The price of the order
        /// </summary>
        [JsonPropertyName("price")]
        public decimal Price
        {
            get
            {
                if (_price == 0 && Type == SpotOrderType.Market && QuantityFilled != 0)
                    return QuoteQuantityFilled / QuantityFilled;
                return _price;
            }
            set => _price = value;
        }

        /// <summary>
        /// ["<c>origQty</c>"] The original quantity of the order, as specified in the order parameters by the user
        /// </summary>
        [JsonPropertyName("origQty")]
        public decimal Quantity { get; set; }
        /// <summary>
        /// ["<c>executedQty</c>"] The currently executed quantity of the order
        /// </summary>
        [JsonPropertyName("executedQty")]
        public decimal QuantityFilled { get; set; }
        /// <summary>
        /// ["<c>cummulativeQuoteQty</c>"] The currently executed amount of quote asset. Amounts to Sum(quantity * price) of executed trades for this order
        /// </summary>
        [JsonPropertyName("cummulativeQuoteQty")]
        public decimal QuoteQuantityFilled { get; set; }
        /// <summary>
        /// ["<c>origQuoteOrderQty</c>"] The original quote order quantity of the order, as specified in the order parameters by the user
        /// </summary>
        [JsonPropertyName("origQuoteOrderQty")]
        public decimal QuoteQuantity { get; set; }

        /// <summary>
        /// ["<c>status</c>"] The status of the order
        /// </summary>
        [JsonPropertyName("status")]
        public OrderStatus Status { get; set; }

        /// <summary>
        /// ["<c>timeInForce</c>"] How long the order is active
        /// </summary>
        [JsonPropertyName("timeInForce")]
        public TimeInForce TimeInForce { get; set; }
        /// <summary>
        /// ["<c>type</c>"] The type of the order
        /// </summary>
        [JsonPropertyName("type")]
        public SpotOrderType Type { get; set; }
        /// <summary>
        /// ["<c>side</c>"] The side of the order
        /// </summary>
        [JsonPropertyName("side")]
        public OrderSide Side { get; set; }
        /// <summary>
        /// ["<c>stopPrice</c>"] The stop price
        /// </summary>
        [JsonPropertyName("stopPrice")]
        public decimal? StopPrice { get; set; }
        /// <summary>
        /// ["<c>trailingDelta</c>"] Trailing delta
        /// </summary>
        [JsonPropertyName("trailingDelta")]
        public int? TrailingDelta { get; set; }
        /// <summary>
        /// ["<c>trailingTime</c>"] Trailing delta time
        /// </summary>
        [JsonPropertyName("trailingTime")]
        public DateTime? TrailingTime { get; set; }
        /// <summary>
        /// ["<c>strategyId</c>"] Strategy id
        /// </summary>
        [JsonPropertyName("strategyId")]
        public long? StrategyId { get; set; }
        /// <summary>
        /// ["<c>strategyType</c>"] Strategy type
        /// </summary>
        [JsonPropertyName("strategyType")]
        public long? StrategyType { get; set; }
        /// <summary>
        /// ["<c>icebergQty</c>"] The iceberg quantity
        /// </summary>
        [JsonPropertyName("icebergQty")]
        public decimal? IcebergQuantity { get; set; }
        /// <summary>
        /// ["<c>time</c>"] The time the order was submitted
        /// </summary>
        [JsonPropertyName("time"), JsonConverter(typeof(DateTimeConverter))]
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// ["<c>updateTime</c>"] The time the order was last updated
        /// </summary>
        [JsonConverter(typeof(DateTimeConverter))]
        [JsonPropertyName("updateTime")]
        public DateTime? UpdateTime { get; set; }
        /// <summary>
        /// ["<c>transactTime</c>"] The time the transaction was executed (when canceling order)
        /// </summary>
        [JsonConverter(typeof(DateTimeConverter))]
        [JsonPropertyName("transactTime")]
        public DateTime? TransactTime { get; set; }
        /// <summary>
        /// ["<c>workingTime</c>"] When the order started working
        /// </summary>
        [JsonConverter(typeof(DateTimeConverter))]
        [JsonPropertyName("workingTime")]
        public DateTime? WorkingTime { get; set; }
        /// <summary>
        /// ["<c>isWorking</c>"] Is working
        /// </summary>
        [JsonPropertyName("isWorking")]
        public bool? IsWorking { get; set; }
        /// <summary>
        /// ["<c>isIsolated</c>"] If isolated margin (for margin account orders)
        /// </summary>
        [JsonPropertyName("isIsolated")]
        public bool? IsIsolated { get; set; }
        /// <summary>
        /// Quantity which is still open to be filled
        /// </summary>
        public decimal QuantityRemaining => Quantity - QuantityFilled;

        /// <summary>
        /// The average price the order was filled
        /// </summary>
        public decimal? AverageFillPrice
        {
            get
            {
                if (QuantityFilled == 0)
                    return null;

                return QuoteQuantityFilled / QuantityFilled;
            }
        }

        /// <summary>
        /// ["<c>selfTradePreventionMode</c>"] Self trade prevention mode
        /// </summary>
        [JsonPropertyName("selfTradePreventionMode")]
        public SelfTradePreventionMode SelfTradePreventionMode { get; set; }

        /// <summary>
        /// ["<c>preventedMatchId</c>"] Prevented self trade match id
        /// </summary>
        [JsonPropertyName("preventedMatchId")]
        public long? PreventedMatchId { get; set; }
        /// <summary>
        /// ["<c>preventedQuantity</c>"] Prevented self trade quantity
        /// </summary>
        [JsonPropertyName("preventedQuantity")]
        public decimal? PreventedMatchQuantity { get; set; }
        /// <summary>
        /// ["<c>pegPriceType</c>"] Peg price type
        /// </summary>
        [JsonPropertyName("pegPriceType")]
        public PegPriceType? PegPriceType { get; set; }
        /// <summary>
        /// ["<c>pegOffsetValue</c>"] Peg offset value
        /// </summary>
        [JsonPropertyName("pegOffsetValue")]
        public int? PegOffsetValue { get; set; }
        /// <summary>
        /// ["<c>pegOffsetType</c>"] Peg offset type
        /// </summary>
        [JsonPropertyName("pegOffsetType")]
        public PegOffsetType? PegOffsetType { get; set; }
        /// <summary>
        /// ["<c>peggedPrice</c>"] Pegged price
        /// </summary>
        [JsonPropertyName("peggedPrice")]
        public decimal? PeggedPrice { get; set; }
    }
}

