using Binance.Net.Enums;
using Binance.Net.Objects.Internal;
using Binance.Net.Objects.Models;
using Binance.Net.Objects.Models.Futures;
using Binance.Net.Objects.Models.Futures.AlgoOrders;
using Binance.Net.Objects.Models.Futures.Socket;
using Binance.Net.Objects.Models.Spot;
using Binance.Net.Objects.Models.Spot.AutoInvest;
using Binance.Net.Objects.Models.Spot.Blvt;
using Binance.Net.Objects.Models.Spot.Brokerage.SubAccountData;
using Binance.Net.Objects.Models.Spot.Convert;
using Binance.Net.Objects.Models.Spot.CopyTrading;
using Binance.Net.Objects.Models.Spot.IsolatedMargin;
using Binance.Net.Objects.Models.Spot.Loans;
using Binance.Net.Objects.Models.Spot.Margin;
using Binance.Net.Objects.Models.Spot.Mining;
using Binance.Net.Objects.Models.Spot.PortfolioMargin;
using Binance.Net.Objects.Models.Spot.SimpleEarn;
using Binance.Net.Objects.Models.Spot.Socket;
using Binance.Net.Objects.Models.Spot.Staking;
using Binance.Net.Objects.Models.Spot.SubAccountData;
using Binance.Net.Objects.Sockets;

namespace Binance.Net.Converters
{
    // Standard types
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    
    // Internal
    [JsonSerializable(typeof(BinanceSocketRequest))]
    [JsonSerializable(typeof(BinanceSocketQuery))]

    // Models.Futures.AlgoOrders
    [JsonSerializable(typeof(BinanceAlgoOrders))]
    [JsonSerializable(typeof(BinanceAlgoOrderResult))]
    [JsonSerializable(typeof(BinanceAlgoResult))]
    [JsonSerializable(typeof(BinanceAlgoSubOrderList))]

    // Models.Futures.Socket
    [JsonSerializable(typeof(BinanceConditionOrderTriggerRejectUpdate))]
    [JsonSerializable(typeof(BinanceFuturesStreamAccountUpdate))]
    [JsonSerializable(typeof(BinanceFuturesStreamAssetIndexUpdate))]
    [JsonSerializable(typeof(BinanceFuturesStreamBookPrice))]
    [JsonSerializable(typeof(BinanceFuturesStreamCoinKlineData))]
    [JsonSerializable(typeof(BinanceFuturesStreamCoinKline))]
    [JsonSerializable(typeof(BinanceFuturesStreamCompositeIndex))]
    [JsonSerializable(typeof(BinanceFuturesStreamConfigUpdate))]
    [JsonSerializable(typeof(BinanceStreamContinuousKlineData))]
    [JsonSerializable(typeof(BinanceStreamIndexKlineData))]
    [JsonSerializable(typeof(BinanceFuturesStreamIndexPrice))]
    [JsonSerializable(typeof(BinanceFuturesStreamLiquidationData))]
    [JsonSerializable(typeof(BinanceFuturesStreamMarginUpdate))]
    [JsonSerializable(typeof(BinanceFuturesStreamMarkPrice))]
    [JsonSerializable(typeof(BinanceFuturesUsdtStreamMarkPrice))]
    [JsonSerializable(typeof(BinanceFuturesCoinStreamMarkPrice))]
    [JsonSerializable(typeof(BinanceFuturesStreamOrderBookDepth))]
    [JsonSerializable(typeof(BinanceFuturesStreamOrderUpdate))]
    [JsonSerializable(typeof(BinanceFuturesStreamSymbolUpdate))]
    [JsonSerializable(typeof(BinanceFuturesStreamTradeUpdate))]
    [JsonSerializable(typeof(BinanceGridUpdate))]
    [JsonSerializable(typeof(BinanceStrategyUpdate))]

    // Models.Futures
    [JsonSerializable(typeof(BinanceFuturesBnbBurnStatus[]))]
    [JsonSerializable(typeof(BinanceFuturesAccountAsset[]))]
    [JsonSerializable(typeof(BinanceFuturesAccountBalance[]))]
    [JsonSerializable(typeof(BinanceUsdFuturesAccountBalance[]))]
    [JsonSerializable(typeof(BinanceCoinFuturesAccountBalance[]))]
    [JsonSerializable(typeof(BinanceFuturesAccountConfiguration[]))]
    [JsonSerializable(typeof(BinanceFuturesAccountInfo[]))]
    [JsonSerializable(typeof(BinanceFuturesAccountInfoV3[]))]
    [JsonSerializable(typeof(BinanceFuturesAccountUserCommissionRate[]))]
    [JsonSerializable(typeof(BinanceFuturesAssetIndex[]))]
    [JsonSerializable(typeof(BinanceFuturesBasis[]))]
    [JsonSerializable(typeof(BinanceFuturesBatchEditOrder[]))]
    [JsonSerializable(typeof(BinanceFuturesBatchOrder[]))]
    [JsonSerializable(typeof(BinanceFuturesBookPrice[]))]
    [JsonSerializable(typeof(BinanceFuturesBuySellVolumeRatio[]))]
    [JsonSerializable(typeof(BinanceFuturesCancelAllOrders[]))]
    [JsonSerializable(typeof(BinanceFuturesChangeMarginTypeResult[]))]
    [JsonSerializable(typeof(BinanceFuturesCoin24HPrice[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinAccountInfo[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinBuySellVolumeRatio[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinKline[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinOpenInterestHistory[]))]
    [JsonSerializable(typeof(BinanceFuturesCompositeIndexInfo[]))]
    [JsonSerializable(typeof(BinanceFuturesConvertQuote[]))]
    [JsonSerializable(typeof(BinanceFuturesConvertStatus[]))]
    [JsonSerializable(typeof(BinanceFuturesConvertSymbol[]))]
    [JsonSerializable(typeof(BinanceFuturesCountDownResult[]))]
    [JsonSerializable(typeof(BinanceFuturesDownloadIdInfo[]))]
    [JsonSerializable(typeof(BinanceFuturesDownloadLink[]))]
    [JsonSerializable(typeof(BinanceFuturesUsdtExchangeInfo[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinExchangeInfo[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinSymbol[]))]
    [JsonSerializable(typeof(BinanceFuturesUsdtSymbol[]))]
    [JsonSerializable(typeof(BinanceFuturesFundingInfo[]))]
    [JsonSerializable(typeof(BinanceFuturesFundingRateHistory[]))]
    [JsonSerializable(typeof(BinanceFuturesIncomeHistory[]))]
    [JsonSerializable(typeof(BinanceFuturesInitialLeverageChangeResult[]))]
    [JsonSerializable(typeof(BinanceFuturesLongShortRatio[]))]
    [JsonSerializable(typeof(BinanceFuturesMarginChangeHistoryResult[]))]
    [JsonSerializable(typeof(BinanceFuturesMarkPrice[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinMarkPrice[]))]
    [JsonSerializable(typeof(BinanceFuturesMultiAssetMode[]))]
    [JsonSerializable(typeof(BinanceFuturesMultipleOrderCancelResult[]))]
    [JsonSerializable(typeof(BinanceUsdFuturesMultipleOrderCancelResult[]))]
    [JsonSerializable(typeof(BinanceFuturesMultipleOrderPlaceResult[]))]
    [JsonSerializable(typeof(BinanceUsdFuturesMultipleOrderPlaceResult[]))]
    [JsonSerializable(typeof(BinanceFuturesOpenInterest[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinOpenInterest[]))]
    [JsonSerializable(typeof(BinanceFuturesOpenInterestHistory[]))]
    [JsonSerializable(typeof(BinanceFuturesOrder[]))]
    [JsonSerializable(typeof(BinanceUsdFuturesOrder[]))]
    [JsonSerializable(typeof(BinanceFuturesOrderBook[]))]
    [JsonSerializable(typeof(BinanceFuturesOrderEditHistory[]))]
    [JsonSerializable(typeof(BinanceFuturesPositionMarginResult[]))]
    [JsonSerializable(typeof(BinanceFuturesPositionMode[]))]
    [JsonSerializable(typeof(BinanceFuturesQuantileEstimation[]))]
    [JsonSerializable(typeof(BinanceFuturesQuoteResult[]))]
    [JsonSerializable(typeof(BinanceFuturesSymbolBracket[]))]
    [JsonSerializable(typeof(BinanceFuturesTrade[]))]
    [JsonSerializable(typeof(BinanceFuturesUsdtTrade[]))]
    [JsonSerializable(typeof(BinanceFuturesCoinTrade[]))]
    [JsonSerializable(typeof(BinanceFuturesTradingStatus[]))]
    [JsonSerializable(typeof(BinanceFuturesUsdtAsset[]))]
    [JsonSerializable(typeof(BinanceFuturesUsdtKline[]))]
    [JsonSerializable(typeof(BinanceFuturesIfNewUser[]))]
    [JsonSerializable(typeof(BinancePositionBase[]))]
    [JsonSerializable(typeof(BinancePositionInfoBase[]))]
    [JsonSerializable(typeof(BinancePositionInfoUsdt[]))]
    [JsonSerializable(typeof(BinancePositionInfoCoin[]))]
    [JsonSerializable(typeof(BinancePositionDetailsBase[]))]
    [JsonSerializable(typeof(BinancePositionDetailsUsdt[]))]
    [JsonSerializable(typeof(BinancePositionDetailsCoin[]))]
    [JsonSerializable(typeof(BinancePositionV3[]))]
    [JsonSerializable(typeof(BinanceSymbolConfiguration[]))]

    // Models.Spot.AutoInvest
    [JsonSerializable(typeof(BinanceAutoInvestAssets))]
    [JsonSerializable(typeof(BinanceAutoInvestEditResult))]
    [JsonSerializable(typeof(BinanceAutoInvestEditStatusResult))]
    [JsonSerializable(typeof(BinanceAutoInvestIndex))]
    [JsonSerializable(typeof(BinanceAutoInvestIndexPlanPosition))]
    [JsonSerializable(typeof(BinanceAutoInvestOneTimeTransactionStatus))]
    [JsonSerializable(typeof(BinanceAutoInvestPlan))]
    [JsonSerializable(typeof(BinanceAutoInvestPlanHoldings))]
    [JsonSerializable(typeof(BinanceAutoInvestPlanTransactions))]
    [JsonSerializable(typeof(BinanceAutoInvestRebalanceInfo))]
    [JsonSerializable(typeof(BinanceAutoInvestRedemption))]
    [JsonSerializable(typeof(BinanceAutoInvestRedemptionResult))]
    [JsonSerializable(typeof(BinanceAutoInvestRoi))]
    [JsonSerializable(typeof(BinanceAutoInvestSourceAssets))]
    [JsonSerializable(typeof(BinanceAutoInvestTargetAssets))]
    [JsonSerializable(typeof(BinanceAutoInvestTradeResult))]

    // Models.Spot.Blvt
    [JsonSerializable(typeof(BinanceBlvtInfo))]
    [JsonSerializable(typeof(BinanceBlvtInfoUpdate))]
    [JsonSerializable(typeof(BinanceBlvtKline))]
    [JsonSerializable(typeof(BinanceBlvtRedeemResult))]
    [JsonSerializable(typeof(BinanceBlvtRedemption))]
    [JsonSerializable(typeof(BinanceBlvtSubscribeResult))]
    [JsonSerializable(typeof(BinanceBlvtSubscription))]
    [JsonSerializable(typeof(BinanceBlvtUserLimit))]

    // Models.Spot.Brokerage
    [JsonSerializable(typeof(BinanceBrokerageAccountInfo))]
    [JsonSerializable(typeof(BinanceBrokerageAddIpRestrictionResult))]
    [JsonSerializable(typeof(BinanceBrokerageApiKeyCreateResult))]
    [JsonSerializable(typeof(BinanceBrokerageBnbBurnStatus))]
    [JsonSerializable(typeof(BinanceBrokerageChangeBnbBurnMarginInterestResult))]
    [JsonSerializable(typeof(BinanceBrokerageChangeBnbBurnSpotAndMarginResult))]
    [JsonSerializable(typeof(BinanceBrokerageEnableFuturesResult))]
    [JsonSerializable(typeof(BinanceBrokerageEnableLeverageTokenResult))]
    [JsonSerializable(typeof(BinanceBrokerageEnableMarginResult))]
    [JsonSerializable(typeof(BinanceBrokerageFuturesAssetInfo))]
    [JsonSerializable(typeof(BinanceBrokerageFuturesRebate))]
    [JsonSerializable(typeof(BinanceBrokerageIpRestrictionBase))]
    [JsonSerializable(typeof(BinanceBrokerageIpRestriction))]
    [JsonSerializable(typeof(BinanceBrokerageMarginAssetInfo))]
    [JsonSerializable(typeof(BinanceBrokerageRebate))]
    [JsonSerializable(typeof(BinanceBrokerageSpotAssetInfo))]
    [JsonSerializable(typeof(BinanceBrokerageSubAccount))]
    [JsonSerializable(typeof(BinanceBrokerageSubAccountApiKey))]
    [JsonSerializable(typeof(BinanceBrokerageSubAccountCoinFuturesCommission))]
    [JsonSerializable(typeof(BinanceBrokerageSubAccountCommission))]
    [JsonSerializable(typeof(BinanceBrokerageSubAccountCreateResult))]
    [JsonSerializable(typeof(BinanceBrokerageSubAccountDepositTransaction))]
    [JsonSerializable(typeof(BinanceBrokerageSubAccountFuturesCommission))]
    [JsonSerializable(typeof(BinanceBrokerageTransferFuturesResult))]
    [JsonSerializable(typeof(BinanceBrokerageTransferFuturesTransactions))]
    [JsonSerializable(typeof(BinanceBrokerageTransferResult))]
    [JsonSerializable(typeof(BinanceBrokerageTransferTransaction))]
    [JsonSerializable(typeof(BinanceBrokerageTransferTransactionUniversal))]

    // Models.Spot.Convert
    [JsonSerializable(typeof(BinanceConvertAssetPair))]
    [JsonSerializable(typeof(BinanceConvertOrderStatus))]
    [JsonSerializable(typeof(BinanceConvertQuantityPrecisionAsset))]
    [JsonSerializable(typeof(BinanceConvertQuote))]
    [JsonSerializable(typeof(BinanceConvertResult))]
    [JsonSerializable(typeof(BinanceConvertTrade))]

    // Models.Spot.CopyTrading
    [JsonSerializable(typeof(BinanceCopyTradingLeadSymbol))]
    [JsonSerializable(typeof(BinanceCopyTradingUserStatus))]

    // Models.Spot.IsolatedMargin
    [JsonSerializable(typeof(BinanceIsolatedMarginSymbol))]
    [JsonSerializable(typeof(CreateIsolatedMarginAccountResult))]
    [JsonSerializable(typeof(BinanceIsolatedMarginAccount))]
    [JsonSerializable(typeof(IsolatedMarginAccountLimit))]

    // Models.Spot.Loans
    [JsonSerializable(typeof(BinanceCryptoLoanAsset))]
    [JsonSerializable(typeof(BinanceCryptoLoanBorrow))]
    [JsonSerializable(typeof(BinanceCryptoLoanBorrowRecord))]
    [JsonSerializable(typeof(BinanceCryptoLoanCollateralAsset))]
    [JsonSerializable(typeof(BinanceCryptoLoanIncome))]
    [JsonSerializable(typeof(BinanceCryptoLoanLtvAdjust))]
    [JsonSerializable(typeof(BinanceCryptoLoanLtvAdjustRecord))]
    [JsonSerializable(typeof(BinanceCryptoLoanMarginCallResult))]
    [JsonSerializable(typeof(BinanceCryptoLoanOpenBorrowOrder))]
    [JsonSerializable(typeof(BinanceCryptoLoanRepay))]
    [JsonSerializable(typeof(BinanceCryptoLoanRepayRate))]
    [JsonSerializable(typeof(BinanceCryptoLoanRepayRecord))]

    // Models.Spot.Margin
    [JsonSerializable(typeof(BinanceCrossMarginCollateralRatio))]
    [JsonSerializable(typeof(BinanceCrossMarginLeverageResult))]
    [JsonSerializable(typeof(BinanceForcedLiquidation))]
    [JsonSerializable(typeof(BinanceFuturesInterestRate))]
    [JsonSerializable(typeof(BinanceInterestHistory))]
    [JsonSerializable(typeof(BinanceInterestMarginData))]
    [JsonSerializable(typeof(BinanceInterestRateHistory))]
    [JsonSerializable(typeof(BinanceIsolatedMarginFeeData))]
    [JsonSerializable(typeof(BinanceIsolatedMarginTierData))]
    [JsonSerializable(typeof(BinanceMarginAccount))]
    [JsonSerializable(typeof(BinanceMarginAccountSnapshot))]
    [JsonSerializable(typeof(BinanceMarginAmount))]
    [JsonSerializable(typeof(BinanceMarginAsset))]
    [JsonSerializable(typeof(BinanceMarginDelistSchedule))]
    [JsonSerializable(typeof(BinanceMarginDustAsset))]
    [JsonSerializable(typeof(BinanceMarginDustTransfer))]
    [JsonSerializable(typeof(BinanceMarginLevel))]
    [JsonSerializable(typeof(BinanceMarginOrderOcoList))]
    [JsonSerializable(typeof(BinanceMarginPair))]
    [JsonSerializable(typeof(BinanceMarginPriceIndex))]
    [JsonSerializable(typeof(BinanceTransaction))]
    [JsonSerializable(typeof(BinanceLoan))]
    [JsonSerializable(typeof(BinanceRepay))]
    [JsonSerializable(typeof(BinanceSmallLiabilityAsset))]
    [JsonSerializable(typeof(BinanceSmallLiabilityHistory))]
    [JsonSerializable(typeof(BinanceTransferHistory))]

    // Models.Spot.Mining
    [JsonSerializable(typeof(BinanceHashrateResaleDetails))]
    [JsonSerializable(typeof(BinanceHashrateResaleList))]
    [JsonSerializable(typeof(BinanceMinerList))]
    [JsonSerializable(typeof(BinanceMinerDetails))]
    [JsonSerializable(typeof(BinanceMiningAccount))]
    [JsonSerializable(typeof(BinanceMiningAlgorithm))]
    [JsonSerializable(typeof(BinanceMiningCoin))]
    [JsonSerializable(typeof(BinanceMiningEarnings))]
    [JsonSerializable(typeof(BinanceMiningStatistic))]
    [JsonSerializable(typeof(BinanceOtherRevenueList))]
    [JsonSerializable(typeof(BinanceRevenueList))]

    // Models.Spot.PortfolioMargin
    [JsonSerializable(typeof(BinancePortfolioMarginCollateralRate))]
    [JsonSerializable(typeof(BinancePortfolioMarginInfo))]
    [JsonSerializable(typeof(BinancePortfolioMarginLoan))]

    // Models.Spot.SimpleEarn
    [JsonSerializable(typeof(BinanceSimpleEarnAccount))]
    [JsonSerializable(typeof(BinanceSimpleEarnCollateralRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnFlexiblePosition))]
    [JsonSerializable(typeof(BinanceSimpleEarnFlexiblePreview))]
    [JsonSerializable(typeof(BinanceSimpleEarnFlexibleProduct))]
    [JsonSerializable(typeof(BinanceSimpleEarnFlexibleRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnFlexibleRedemptionRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnFlexibleRewardRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnLockedPosition))]
    [JsonSerializable(typeof(BinanceSimpleEarnLockedPreview))]
    [JsonSerializable(typeof(BinanceSimpleEarnLockedProduct))]
    [JsonSerializable(typeof(BinanceSimpleEarnLockedRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnLockedRedemptionRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnLockedRewardRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnPersonalQuotaLeft))]
    [JsonSerializable(typeof(BinanceSimpleEarnPurchase))]
    [JsonSerializable(typeof(BinanceSimpleEarnRateRecord))]
    [JsonSerializable(typeof(BinanceSimpleEarnRedemption))]
    [JsonSerializable(typeof(BinanceSimpleEarnResult))]

    // Models.Spot.Socket
    [JsonSerializable(typeof(BinanceStreamAggregatedTrade))]
    [JsonSerializable(typeof(BinanceStreamBalanceLockUpdate))]
    [JsonSerializable(typeof(BinanceStreamBalanceUpdate))]
    [JsonSerializable(typeof(BinanceStreamBookPrice))]
    [JsonSerializable(typeof(BinanceStreamKlineData))]
    [JsonSerializable(typeof(BinanceStreamKline))]
    [JsonSerializable(typeof(BinanceStreamMiniTickBase))]
    [JsonSerializable(typeof(BinanceStreamMiniTick))]
    [JsonSerializable(typeof(BinanceStreamCoinMiniTick))]
    [JsonSerializable(typeof(BinanceStreamOrderList))]
    [JsonSerializable(typeof(BinanceStreamOrderUpdate))]
    [JsonSerializable(typeof(BinanceStreamPositionsUpdate))]
    [JsonSerializable(typeof(BinanceStreamRollingWindowTick))]
    [JsonSerializable(typeof(BinanceStreamTickBase))]
    [JsonSerializable(typeof(BinanceStreamTick))]
    [JsonSerializable(typeof(BinanceStreamCoinTick))]
    [JsonSerializable(typeof(BinanceStreamTrade))]

    // Models.Spot.Staking
    [JsonSerializable(typeof(BinanceBethRateHistory))]
    [JsonSerializable(typeof(BinanceBethWrapHistory))]
    [JsonSerializable(typeof(BinanceBnsolRateHistory))]
    [JsonSerializable(typeof(BinanceBnsolRewardHistory))]
    [JsonSerializable(typeof(BinanceEthRewardsHistory))]
    [JsonSerializable(typeof(BinanceEthStakingAccount))]
    [JsonSerializable(typeof(BinanceEthStakingQuota))]
    [JsonSerializable(typeof(BinanceRedemptionHistory))]
    [JsonSerializable(typeof(BinanceSolRewards))]
    [JsonSerializable(typeof(BinanceSolReward))]
    [JsonSerializable(typeof(BinanceSolStakingAccount))]
    [JsonSerializable(typeof(BinanceSolStakingQuota))]
    [JsonSerializable(typeof(BinanceSolStakingResult))]
    [JsonSerializable(typeof(BinanceSolUnclaimedReward))]
    [JsonSerializable(typeof(BinanceStakingHistory))]
    [JsonSerializable(typeof(BinanceStakingResult))]

    // Models.Spot.SubAccountData
    [JsonSerializable(typeof(BinanceSubAccountWrapper))]
    [JsonSerializable(typeof(BinanceSubAccountAsset))]
    [JsonSerializable(typeof(BinanceSubAccountAssetTransferHistoryList))]
    [JsonSerializable(typeof(BinanceSubAccountBlvt))]
    [JsonSerializable(typeof(BinanceSubAccountDeposit))]
    [JsonSerializable(typeof(BinanceSubAccountDepositAddress))]
    [JsonSerializable(typeof(BinanceSubAccountEmail))]
    [JsonSerializable(typeof(BinanceSubAccountFuturesDetails))]
    [JsonSerializable(typeof(BinanceSubAccountFuturesDetailsV2))]
    [JsonSerializable(typeof(BinanceSubAccountFuturesEnabled))]
    [JsonSerializable(typeof(BinanceSubAccountFuturesPositionRisk))]
    [JsonSerializable(typeof(BinanceSubAccountFuturesPositionRiskV2))]
    [JsonSerializable(typeof(BinanceSubAccountMarginDetails))]
    [JsonSerializable(typeof(BinanceSubAccountMarginEnabled))]
    [JsonSerializable(typeof(BinanceSubAccountsFuturesSummary))]
    [JsonSerializable(typeof(BinanceSubAccountsMarginSummary))]
    [JsonSerializable(typeof(BinanceSubAccountSpotAssetsSummary))]
    [JsonSerializable(typeof(BinanceSubAccountStatus))]
    [JsonSerializable(typeof(BinanceSubAccountTransaction))]
    [JsonSerializable(typeof(BinanceSubAccountTransfer))]
    [JsonSerializable(typeof(BinanceSubAccountTransferSubAccount))]
    [JsonSerializable(typeof(BinanceSubAccountUniversalTransfersList))]

    // Models.Spot
    [JsonSerializable(typeof(Binance24HPrice))]
    [JsonSerializable(typeof(BinanceAccountInfo))]
    [JsonSerializable(typeof(BinanceAccountStatus))]
    [JsonSerializable(typeof(BinanceAggregatedTrade))]
    [JsonSerializable(typeof(BinanceAPIKeyPermissions))]
    [JsonSerializable(typeof(BinanceAveragePrice))]
    [JsonSerializable(typeof(BinanceBnbBurnStatus))]
    [JsonSerializable(typeof(BinanceBookPrice))]
    [JsonSerializable(typeof(BinanceBusdHistory))]
    [JsonSerializable(typeof(BinanceC2CUserTrade))]
    [JsonSerializable(typeof(BinanceCheckTime))]
    [JsonSerializable(typeof(BinanceCloudMiningHistory))]
    [JsonSerializable(typeof(BinanceCommissions))]
    [JsonSerializable(typeof(BinanceDelistSchedule))]
    [JsonSerializable(typeof(BinanceDepositAddress))]
    [JsonSerializable(typeof(BinanceDeposit))]
    [JsonSerializable(typeof(BinanceDividendRecord))]
    [JsonSerializable(typeof(BinanceDustLogList))]
    [JsonSerializable(typeof(BinanceDustTransferResult))]
    [JsonSerializable(typeof(BinanceEligibleDusts))]
    [JsonSerializable(typeof(BinanceEventOrderBook))]
    [JsonSerializable(typeof(BinanceExchangeInfo))]
    [JsonSerializable(typeof(BinanceFiatPayment))]
    [JsonSerializable(typeof(BinanceFiatWithdrawDeposit))]
    [JsonSerializable(typeof(BinanceFundingAsset))]
    [JsonSerializable(typeof(BinanceFuturesAccountSnapshot))]
    [JsonSerializable(typeof(BinanceIfNewUser))]
    [JsonSerializable(typeof(BinanceIpRestriction))]
    [JsonSerializable(typeof(BinanceListenKey))]
    [JsonSerializable(typeof(BinanceMarkIndexKline))]
    [JsonSerializable(typeof(BinanceOrder))]
    [JsonSerializable(typeof(BinanceOrderBook))]
    [JsonSerializable(typeof(BinanceOrderOcoList))]
    [JsonSerializable(typeof(BinanceCurrentRateLimit))]
    [JsonSerializable(typeof(BinanceOrderTrade))]
    [JsonSerializable(typeof(BinancePayTrade))]
    [JsonSerializable(typeof(BinancePlacedOrder))]
    [JsonSerializable(typeof(BinancePreventedTrade))]
    [JsonSerializable(typeof(BinancePrice))]
    [JsonSerializable(typeof(BinanceFuturesCoinPrice))]
    [JsonSerializable(typeof(BinanceProduct))]
    [JsonSerializable(typeof(BinanceRebateWrapper))]
    [JsonSerializable(typeof(BinanceRecentTrade))]
    [JsonSerializable(typeof(BinanceReplaceOrderResult))]
    [JsonSerializable(typeof(BinanceSpotAccountSnapshot))]
    [JsonSerializable(typeof(BinanceSpotFuturesTransfer))]
    [JsonSerializable(typeof(BinanceSpotKline))]
    [JsonSerializable(typeof(BinanceSymbol))]
    [JsonSerializable(typeof(BinanceSystemStatus))]
    [JsonSerializable(typeof(BinanceTestOrderCommission))]
    [JsonSerializable(typeof(BinanceTrade))]
    [JsonSerializable(typeof(BinanceTradeFee))]
    [JsonSerializable(typeof(BinanceTradingDayTicker))]
    [JsonSerializable(typeof(BinanceTradingStatus))]
    [JsonSerializable(typeof(BinanceTransfer))]
    [JsonSerializable(typeof(BinanceUserAsset))]
    [JsonSerializable(typeof(BinanceUserBalance))]
    [JsonSerializable(typeof(BinanceVipLevelAndStatus))]
    [JsonSerializable(typeof(BinanceWalletBalance))]
    [JsonSerializable(typeof(BinanceWithdrawal))]
    [JsonSerializable(typeof(BinanceWithdrawalAddress))]
    [JsonSerializable(typeof(BinanceAssetDetails))]
    [JsonSerializable(typeof(BinanceWithdrawalPlaced))]

    // Models
    [JsonSerializable(typeof(BinanceOrderBase))]
    [JsonSerializable(typeof(BinanceOrderBookEntry))]
    [JsonSerializable(typeof(BinanceRateLimit))]
    [JsonSerializable(typeof(BinanceResult))]
    [JsonSerializable(typeof(BinanceRollingWindowTick))]
    [JsonSerializable(typeof(BinanceStreamEvent))]

    // Sockets
    [JsonSerializable(typeof(BinanceSocketQueryResponse))]

    // Generic types
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamSymbolUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesCoinStreamMarkPrice[]>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamBookPrice>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamCoinKlineData>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamLiquidationData>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamOrderBookDepth>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamAggregatedTrade>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamCoinMiniTick[]>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamCoinMiniTick>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamCoinTick[]>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamCoinTick>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamIndexKlineData>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamKlineData>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesCoinStreamMarkPrice>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamIndexPrice>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceEventOrderBook>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceOrderBook>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamBookPrice>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamMiniTick>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamRollingWindowTick[]>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamRollingWindowTick>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamTick[]>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamTick>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamCompositeIndex>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamAssetIndexUpdate[]>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesUsdtStreamMarkPrice[]>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesUsdtStreamMarkPrice>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamContinuousKlineData>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamTrade>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamAccountUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamMarginUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamConfigUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamOrderUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamEvent>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStrategyUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceGridUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamPositionsUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamBalanceUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamOrderUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamOrderList>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamEvent>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceStreamBalanceLockUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceConditionOrderTriggerRejectUpdate>))]
    [JsonSerializable(typeof(BinanceCombinedStream<BinanceFuturesStreamTradeUpdate>))]
    //[JsonSerializable(typeof(BinanceQueryRecords<>))]
    //[JsonSerializable(typeof(BinanceResult<>))]
    //[JsonSerializable(typeof(BinanceListResult<>))]
    //[JsonSerializable(typeof(BinanceExchangeApiWrapper<>))]
    //[JsonSerializable(typeof(BinanceSnapshotWrapper<>))]

    // Enums
    [JsonSerializable(typeof(SymbolFilterType))]

    internal partial class BinanceSourceGenerationContext : JsonSerializerContext
    {
    }
}