namespace Binance.Net
{
    /// <summary>
    /// Binance API credentials
    /// </summary>
    public class BinanceCredentials : ApiCredentials
    {
        /// <summary>
        /// Provided credential type
        /// </summary>
        public ApiCredentialsType CredentialType => CredentialPairs.First().CredentialType;

        /// <summary>
        /// </summary>
        [Obsolete("Parameterless constructor is only for deserialization purposes and should not be used directly. Use parameterized constructor instead.")]
        public BinanceCredentials() { }

        /// <summary>
        /// Create API credentials using an API key and secret generated by the server. This assumes HMAC authentication. If you want to use RSA or Ed25519 authentication, use the appropriate constructor or static method instead.
        /// </summary>
        /// <param name="apiKey">API key</param>
        /// <param name="secret">API secret</param>
        public BinanceCredentials(string apiKey, string secret)
            : this(new HMACCredential(apiKey, secret)) { }

        /// <summary>
        /// Create API credentials using HMAC credentials
        /// </summary>
        /// <param name="hmacCredential">HMAC credentials</param>
        public BinanceCredentials(HMACCredential hmacCredential)
            : base(hmacCredential) 
        {
        }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        /// <summary>
        /// Create Binance credentials using RSA credentials in PEM format
        /// </summary>
        /// <param name="rsaCredential">RSA credentials</param>
        public BinanceCredentials(RSAPemCredential rsaCredential)
            : base(rsaCredential)
        {
        }
#endif
        /// <summary>
        /// Create Binance credentials using RSA credentials in XML format
        /// </summary>
        /// <param name="rsaCredential">RSA credentials</param>
        public BinanceCredentials(RSAXmlCredential rsaCredential)
            : base(rsaCredential)
        {
        }

#if NET8_0_OR_GREATER

        /// <summary>
        /// Create API credentials using ED25519 credentials
        /// </summary>
        /// <param name="ed25519Credential">ED25519 credentials</param>
        public BinanceCredentials(ED25519Credential ed25519Credential)
            : base(ed25519Credential)
        {
        }
#endif

        /// <summary>
        /// Create API credentials using an API key and secret generated by the server
        /// </summary>
        public static BinanceCredentials HmacCredentials(string apiKey, string apiSecret, string? pass = null)
        {
            return new BinanceCredentials(new HMACCredential(apiKey, apiSecret, pass));
        }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        /// <summary>
        /// Create API credentials using an API key and an RSA private key in PEM format
        /// </summary>
        public static BinanceCredentials RsaPemCredentials(string publicKey, string privateKey)
        {
            return new BinanceCredentials(new RSAPemCredential(publicKey, privateKey));
        }
#endif

        /// <summary>
        /// Create API credentials using an API key and an RSA private key in XML format
        /// </summary>
        public static BinanceCredentials RsaXmlCredentials(string publicKey, string privateKey)
        {
            return new BinanceCredentials(new RSAXmlCredential(publicKey, privateKey));
        }

#if NET8_0_OR_GREATER
        /// <summary>
        /// Create API credentials using an API key and an Ed25519 private key
        /// </summary>
        public static BinanceCredentials Ed25519Credentials(string publicKey, string privateKey)
        {
            return new BinanceCredentials(new ED25519Credential(publicKey, privateKey));
        }
#endif

        /// <inheritdoc />
#pragma warning disable CS0618 // Type or member is obsolete
        public override ApiCredentials Copy() => new BinanceCredentials { CredentialPairs = CredentialPairs };
#pragma warning restore CS0618 // Type or member is obsolete
    }
}
