namespace Binance.Net
{
    /// <summary>
    /// Binance API credentials
    /// </summary>
    public class BinanceCredentials : ApiCredentials
    {
        internal CredentialPair? Credential { get; set; }

        public HMACCredential? HMAC
        {
            get => Credential as HMACCredential;
            set { if (value != null) Credential = value; }
        }

        public RSAXmlCredential? RSAXml
        {
            get => Credential as RSAXmlCredential;
            set { if (value != null) Credential = value; }
        }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        public RSAPemCredential? RSAPem
        {
            get => Credential as RSAPemCredential;
            set { if (value != null) Credential = value; }
        }
#endif

#if NET8_0_OR_GREATER
        public Ed25519Credential? Ed25519
        {
            get => Credential as Ed25519Credential;
            set { if (value != null) Credential = value; }
        }
#endif

        public BinanceCredentials WithHMAC(string key, string secret)
        {
            if (Credential != null) throw new InvalidOperationException("Credentials already set");

            Credential = new HMACCredential(key, secret);
            return this;
        }

        public BinanceCredentials WithRSAXml(string key, string privateKey)
        {
            if (Credential != null) throw new InvalidOperationException("Credentials already set");

            Credential = new RSAXmlCredential(key, privateKey);
            return this;
        }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        public BinanceCredentials WithRSAPem(string key, string privateKey)
        {
            if (Credential != null) throw new InvalidOperationException("Credentials already set");

            Credential = new RSAPemCredential(key, privateKey);
            return this;
        }
#endif

#if NET8_0_OR_GREATER
        public BinanceCredentials WithEd25519(string key, string privateKey)
        {
            if (Credential != null) throw new InvalidOperationException("Credentials already set");

            Credential = new Ed25519Credential(key, privateKey);
            return this;
        }
#endif

        /// <inheritdoc />
        public override ApiCredentials Copy() => new BinanceCredentials { Credential = Credential };


        //        /// <summary>
        //        /// Provided credential type
        //        /// </summary>
        //        public ApiCredentialsType CredentialType => CredentialPairs.First().CredentialType;

        //        /// <summary>
        //        /// </summary>
        //        [Obsolete("Parameterless constructor is only for deserialization purposes and should not be used directly. Use parameterized constructor instead.")]
        //        public BinanceCredentials() { }

        //        /// <summary>
        //        /// Create API credentials using an API key and secret generated by the server. This assumes HMAC authentication. If you want to use RSA or Ed25519 authentication, use the appropriate constructor or static method instead.
        //        /// </summary>
        //        /// <param name="apiKey">API key</param>
        //        /// <param name="secret">API secret</param>
        //        public BinanceCredentials(string apiKey, string secret)
        //            : this(new HMACCredential(apiKey, secret)) { }

        //        /// <summary>
        //        /// Create API credentials using HMAC credentials
        //        /// </summary>
        //        /// <param name="hmacCredential">HMAC credentials</param>
        //        public BinanceCredentials(HMACCredential hmacCredential)
        //            : base(hmacCredential) 
        //        {
        //        }

        //#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        //        /// <summary>
        //        /// Create Binance credentials using RSA credentials in PEM format
        //        /// </summary>
        //        /// <param name="rsaCredential">RSA credentials</param>
        //        public BinanceCredentials(RSAPemCredential rsaCredential)
        //            : base(rsaCredential)
        //        {
        //        }
        //#endif
        //        /// <summary>
        //        /// Create Binance credentials using RSA credentials in XML format
        //        /// </summary>
        //        /// <param name="rsaCredential">RSA credentials</param>
        //        public BinanceCredentials(RSAXmlCredential rsaCredential)
        //            : base(rsaCredential)
        //        {
        //        }

        //#if NET8_0_OR_GREATER

        //        /// <summary>
        //        /// Create API credentials using Ed25519 credentials
        //        /// </summary>
        //        /// <param name="ed25519Credential">Ed25519 credentials</param>
        //        public BinanceCredentials(Ed25519Credential ed25519Credential)
        //            : base(ed25519Credential)
        //        {
        //        }
        //#endif

        //        /// <inheritdoc />
        //#pragma warning disable CS0618 // Type or member is obsolete
        //        public override ApiCredentials Copy() => new BinanceCredentials { CredentialPairs = CredentialPairs };
        //#pragma warning restore CS0618 // Type or member is obsolete
    }
}
